name: xo_game
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
flutter_native_splash:
  image: assets/splash.gif

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player: ^2.2.19

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/splash.gif
